---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
  - name: jaeger-ui
    protocol:  TCP
    port: 16686
    targetPort: jaeger-ui
