---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: saleor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: saleor-strg
  resources:
    requests:
      storage: 20Gi
