language: python
sudo: false
python:
  - "3.5"
  - "3.6"
cache:
  pip: true
  directories:
    - node_modules
install:
  - pip install -U pip setuptools wheel
  - pip install tox-travis codecov
  - nvm install 8
  - npm i
  - npm run build-assets --production
  - npm run build-emails
script:
  - tox
env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings
    - DATABASE_URL='postgres://postgres@localhost:5432/saleor'
    - HADOLINT=${HOME}/hadolint
    - HADOLINT_VERSION=1.11.1
    - HADOLINT_URL=https://github.com/hadolint/hadolint/releases/download
  matrix:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="master"
jobs:
  include:
  - stage: lint
    install:
    - curl -sL "${HADOLINT_URL}/v${HADOLINT_VERSION}/hadolint-$(uname -s)-$(uname -m)" -o ${HADOLINT}
    - chmod +x ${HADOLINT}
    script:
    - ${HADOLINT} ./Dockerfile
matrix:
  include:
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.0"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.1"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="master"
  allow_failures:
    - python: "3.5"
      env: DJANGO="2.1"
    - python: "3.5"
      env: DJANGO="master"
    - python: "3.6"
      env: DJANGO="2.1"
    - python: "3.6"
      env: DJANGO="master"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.1"
    - python: "3.7"
      env: DJANGO="master"
      sudo: required
      dist: xenial
after_success:
  - codecov
services:
  - postgresql
