
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: oyelogic:_env(OYE_IMAGE_TAG)
      dockerfile: Dockerfile
      secrets:
        id_rsa:
          type: file
          value: _env(HOME)/.ssh/id_rsa
