version: '3.2'
services:
  redis:
    image: redis
    ports:
      - '6479:6379'

  search:
    image: elasticsearch:5.5
    ports:
      - '9400:9200'
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '14672:15672'
      - '5472:5672'
    volumes:
      - rabbit:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
    command:  bash -c "sleep 10; rabbitmq-server;"
  web:
    image: builder:latest
    entrypoint: /app/docker-entrypoint.sh
#    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    depends_on:
      - redis
      - search
      - rabbitmq
    ports:
      - '8000:8000'
    volumes:
      - /srv/oye.kolter.it/media:/var/www/oye.kolter.it/media

volumes:
  rabbit:
    driver: local
