# fly.toml app configuration file generated for saleor on 2024-01-28T00:52:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'saleor'
primary_region = 'cdg'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  AWS_STORAGE_BUCKET_NAME = 'saleor'
  AWS_MEDIA_BUCKET_NAME = 'saleor'
  AWS_S3_ENDPOINT_URL = 'https://saleor-minio-nginx.fly.dev'
  AWS_S3_USE_SSL = "True"
  AWS_QUERYSTRING_AUTH = "True"
  AWS_S3_FILE_OVERWRITE = "False"
  PORT = '8000'
  ALLOWED_HOSTS = 'saleor.fly.dev'
  ALLOWED_CLIENT_HOSTS = 'saleor.fly.dev'
  PUBLIC_URL = 'https://saleor.fly.dev/'
  DEBUG = "True"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
