blank_issues_enabled: false
contact_links:
  - name: 💬 Spectrum
    url: https://spectrum.chat/dastkari
    about: If you have a support question or need help getting Dastkari to work, please use our Spectrum.
