version: "0.1"

subdomains:
  api-saleor-nullst-one:
    dns_name: api.saleor
    connections:
      domain: nullst-one-domain

apps:
  api:
    module: aws-fargate-service
    vars:
      cpu: 512
      memory: 1024
      port: 8000
    environment:
      ALLOWED_HOSTS: "{{ NULLSTONE_PUBLIC_HOSTS }}"
      BASE_DOMAIN: "dev.nullst.one"
      DASHBOARD_URL: "http://dashboard.saleor.{{ BASE_DOMAIN }}/"
      STOREFRONT_URL: "https://saleor.{{ BASE_DOMAIN }}/"
      CELERY_BROKER_URL: "{{ REDIS_URL }}"
      DATABASE_URL: "{{ POSTGRES_URL }}"
      DEFAULT_CHANNEL_SLUG: "default-channel"
      DEFAULT_FROM_EMAIL: "noreply@example.com"
    capabilities:
      - module: python-cookies
      - module: aws-load-balancer
        vars:
          health_check_interval: 10
          health_check_timeout: 9
          health_check_healthy_threshold: 2
          health_check_unhealthy_threshold: 5
          health_check_path: "/"
        connections:
          subdomain: api-saleor-nullst-one
      - module: aws-postgres-access
        vars:
          database_name: "saleor"
        connections:
          postgres: db
      - module: aws-redis-access
        connections:
          redis: redis
  worker:
    module: aws-fargate-service
    vars:
      cpu: 256
      memory: 512
      port: 0
    environment:
      CELERY_BROKER_URL: "{{ REDIS_URL }}"
      DATABASE_URL: "{{ POSTGRES_URL }}"
      DEFAULT_CHANNEL_SLUG: "default-channel"
      DEFAULT_FROM_EMAIL: "noreply@example.com"
    capabilities:
      - module: aws-postgres-access
        vars:
          database_name: "saleor"
        connections:
          postgres: db

datastores:
  db:
    module: aws-rds-postgres
  redis:
    module: aws-elasticache
