version: "3.4"

services:
  saleor:
    image: saleor/saleor:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: python /app/manage.py runserver 0.0.0.0:8000
    env_file:
      - common.env
      - backend.env
    depends_on:
      - db
      - redis
    volumes:
      - ..:/app
    ports:
      - "8000:8000"

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.20.5
    restart: unless-stopped
    ports:
      - "9000:80"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - saleor-redis:/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # Mailpit UI
    restart: unless-stopped

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
