dependencies:
- name: postgresql
  version: "1.0.0"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  condition: postgresql.enabled,global.postgresql.enabled
- name: redis
  version: "4.2.1"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  condition: redis.enabled,global.redis.enabled
- name: elasticsearch
  version: "1.11.1"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  condition: elasticsearch.enabled,global.elasticsearch.enabled
