name: Deploy PR

on: pull_request

jobs:
  deploy-saleor-pr:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Backend Deployment Link
        uses: bobheadxi/deployments@v0.6.2
        id: deployment_backend
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Preview Backend ${{ github.event.pull_request.number }}
          ref: ${{ github.head_ref }}

      - name: Deploy Saleor
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: w8-saleor-pr-${{ github.event.pull_request.number }}
          heroku_email: "hazem.khaled@gmail.com"
          region: "eu"
          team: "wecre8"
        env:
          HD_ALLOWED_CLIENT_HOSTS: "*"
          HD_ALLOWED_HOSTS: "*"
          HD_DJANGO_SETTINGS_MODULE: "saleor.wecre8_settings"
          HD_DEBUG: "True"
          HD_NPM_CONFIG_PRODUCTION: "false"
          HD_DEFAULT_FROM_EMAIL: "noreply@wecre8.com"
          HD_EMAIL_URL: "${{secrets.EMAIL_URL}}"
          HD_SECRET_KEY: "MESHA_SECRET_KEY"
          HD_AWS_MEDIA_BUCKET_NAME: "${{secrets.AWS_MEDIA_BUCKET_NAME}}"
          HD_AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
          HD_AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
          HD_AWS_STORAGE_BUCKET_NAME: "${{secrets.AWS_STORAGE_BUCKET_NAME}}"
          HD_ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL: "False"

      - name: Seed Data
        run: heroku run python manage.py populatedb --createsuperuser

      - name: Import Cities
        run: heroku run python manage.py cities_light  --force-import-all --keep-slugs
        env:
          HD_DJANGO_SETTINGS_MODULE: "saleor.wecre8_settings"

      - name: Update Backend Deployment Link Status
        if: always()
        uses: bobheadxi/deployments@v0.6.2
        with:
          step: finish
          env_url: https://w8-saleor-pr-${{ github.event.pull_request.number }}.herokuapp.com/graphql/
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          logs: https://w8-saleor-pr-${{ github.event.pull_request.number }}.herokuapp.com/graphql/
          deployment_id: ${{ steps.deployment_backend.outputs.deployment_id }}

  deploy-federation-pr:
    needs: deploy-saleor-pr
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Check out Federation repo
        uses: actions/checkout@v3
        with:
          repository: wecre8-ecommerce/gql-federation-gateway

      - name: Create Gateway Deployment Link
        uses: bobheadxi/deployments@v0.6.2
        id: deployment_gateway
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Preview Gateway ${{ github.event.pull_request.number }}
          ref: ${{ github.head_ref }}

      - name: Deploy Federation
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: w8-pr-${{ github.event.pull_request.number }}
          heroku_email: "hazem.khaled@gmail.com"
          region: "eu"
          team: "wecre8"
          buildpack: heroku/nodejs
        env:
          HD_NODE_ENV: development
          HD_API_URL: https://w8-saleor-pr-${{ github.event.pull_request.number }}.herokuapp.com/
          HD_PLUGINS: social-login,provinces,otp,vendor

      - name: Update Gateway Deployment Link Status
        if: always()
        uses: bobheadxi/deployments@v0.6.2
        with:
          step: finish
          env_url: https://w8-pr-${{ github.event.pull_request.number }}.herokuapp.com//graphql/
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          logs: https://w8-pr-${{ github.event.pull_request.number }}.herokuapp.com//graphql/
          deployment_id: ${{ steps.deployment_gateway.outputs.deployment_id }}
