name: Cleanup PR

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_EMAIL: "hazem.khaled@gmail.com"

      - name: Delete Saleor App
        run: heroku --confirm apps:destroy w8-saleor-pr-${{ github.event.pull_request.number }} --confirm w8-saleor-pr-${{ github.event.pull_request.number }}

      - name: Delete Federation App
        run: heroku --confirm apps:destroy w8-pr-${{ github.event.pull_request.number }} --confirm w8-pr-${{ github.event.pull_request.number }}
