name: Deploy PR

on: pull_request

jobs:
  deploy-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Saleor
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: w8-saleor-pr-${{ github.event.pull_request.number }}
          heroku_email: "hazem.khaled@gmail.com"
          region: "eu"
          team: "wecre8"
        env:
          HD_ALLOWED_CLIENT_HOSTS: "*"
          HD_ALLOWED_HOSTS: "*"
          HD_DJANGO_SETTINGS_MODULE: "saleor.settings"
          HD_DEBUG: "True"
          HD_NPM_CONFIG_PRODUCTION: "false"
          HD_DEFAULT_FROM_EMAIL: "noreply@wecre8.com"
          HD_EMAIL_URL: "${{secrets.EMAIL_URL}}"
          HD_SECRET_KEY: "alibide"
          HD_AWS_MEDIA_BUCKET_NAME: "${{secrets.AWS_MEDIA_BUCKET_NAME}}"
          HD_AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
          HD_AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
          HD_AWS_STORAGE_BUCKET_NAME: "${{secrets.AWS_STORAGE_BUCKET_NAME}}"
          HD_ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL: "False"

      - name: Deploy Federation
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: w8-pr-${{ github.event.pull_request.number }}
          heroku_email: "hazem.khaled@gmail.com"
          region: "eu"
          team: "wecre8"
          buildpack: heroku/nodejs
          appdir: "federation"
        env:
          HD_NODE_ENV: development
          HD_PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Comment deploy links
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Federation: https://w8-pr-${{ github.event.pull_request.number }}.herokuapp.com/
            Backend   : https://w8-saleor-pr-${{ github.event.pull_request.number }}.herokuapp.com/
