# This workflow will build a docker container, publish it to Google Container Registry.

name: Build and Deploy Saleor Staging to GCR

on:
  push:
    branches:
    - yebofresh/staging

# Environment variables available to all jobs and steps in this workflow
env:
  GCR_PROJECT: ${{ secrets.GCR_PROJECT }}
  GCR_EMAIL: ${{ secrets.GCR_EMAIL }}
  GS_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_STAGING }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: saleor-staging
  REGISTRY_HOSTNAME: eu.gcr.io

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '270.0.0'
        service_account_email: $GCR_EMAIL
        service_account_key: ${{ secrets.GCR_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build Core Django App
      run: |
        docker build -t "$REGISTRY_HOSTNAME"/"$GCR_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          --build-arg GS_JSON_ARG="$GS_JSON" yeboyes


    # Push the Docker image to Google Container Registry
    - name: Publish Core Django App
      run: |
        docker push $REGISTRY_HOSTNAME/$GCR_PROJECT/"$IMAGE":$GITHUB_SHA


    # Notify the #deploy channel on Discord of image creation or failure for deploys
    - name: Push Notification to Discord
      uses: sarisia/actions-status-discord@v1.8.6
      if: ${{ success() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Saleor Staging Image Created"
        description: "A Docker image has been created and ready for deploy on Rancher.\n\nImage URL: `${{ env.REGISTRY_HOSTNAME }}/${{ env.GCR_PROJECT }}/${{ env.IMAGE }}:${{ env.GITHUB_SHA }}`"

    - name: Push Failure Notification to Discord
      uses: sarisia/actions-status-discord@v1.8.6
      if: ${{ failure() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Saleor Staging Image Creation"
        description: "There was an error creating the Docker image"
